config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'static_pages/index'

  resources :docs
  authenticated :user do
    root "docs#index", as: "authenticated_root"  #if logged in root is the docs page
  end
  root 'static_pages#index' # if not logged in root is index page
end

app/models/doc.rb
class Doc < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController

before_action :find_doc, only: [:show, :edit, :update, :destroy]

  def index
    @docs = Doc.where(user_id: current_user) #Only show the current user their docs
  end

  def show
  end

  def new
    @doc = current_user.docs.build
  end

  def create
    @doc = current_user.docs.build(doc_params)  # build doc from user ( assign the document to the current user)

    if @doc.save
      redirect_to @doc
    else
      render 'new'
    end

  end

  def edit
  end

  def update
    if @doc.update(doc_params)
      redirect_to @doc
    else
      render 'edit'
    end
  end

  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private

      def find_doc
        @doc = Doc.find(params[:id])  # Find Doc by id
      end

      def doc_params
        params.require(:doc).permit(:title, :content) # List the paramiters permitted
      end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
  = f.input :title
  = f.input :content
  = f.button :submit, class: "button"

app/views/docs/edit.html.haml
.wrapper_with_padding

  %h1 Fix Note

  = render 'form'

  = link_to 'cancel', docs_path

app/views/docs/index.html.haml
.wrapper_with_padding
  #docs.clearfix
    - unless @docs.blank?
      - @docs.each do |doc|
        %a{ href: (url_for [doc])}
          .doc
            %p.title= doc.title
            %p.date= time_ago_in_words(doc.created_at)
            %p.content= truncate(doc.content, length:50)

    - else
      %h2 Create note!
      %button= link_to "Create Note", new_doc_path

app/views/docs/new.html.haml
.wrapper_with_padding
  %h1 New Note

  = render 'form'

app/views/docs/show.html.haml
.wrapper_with_padding
  #doc_show
    %h1= @doc.title
    %p= simple_format(@doc.content)

    .buttons

      =link_to "Fix", edit_doc_path(@doc), class: "button"
      =link_to "Trash", doc_path(@doc), method: :delete, data: {confirm: "are you sure?"} , class: "button"

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Scrap Book | notes and things
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %header
    .header_inner
      = link_to "ScrapBook" , root_path, id: "logo"

      %nav
        -if user_signed_in?
          = link_to "Create Note" , new_doc_path
          = link_to "Sign Out" , destroy_user_session_path, method: :delete

        - else
          = link_to "Log In", new_user_session_path

  %p.notice= notice
  %p.alert= alert

  = yield

app/views/static_pages/index.html.haml
#banner
  .banner_content
    %h1 Scrapbook
    %p Notes and things
    %button= link_to "Sign In", new_user_session_path
    %button= link_to "Sign Up", new_user_registration_path